services:
  postgres:
    image: postgres:16
    container_name: pg
    env_file:
      - .env
    ports:
      - "${PGPORT:-5432}:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro

  app:
    build: ./app
    container_name: birthdays-app
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./app:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"